language: cpp

compiler:
    - gcc

os:
    - linux

dist:
    - xenial

addons:
    apt:
        packages:
        - ninja-build
        - meson
        - libusb-1.0-0-dev
        - libsqlite3-dev
        - g++-7

script:
    - make

