language: c

compiler:
    - gcc

os:
    - linux

dist:
    - xenial

addons:
    apt:
        packages:
        - ninja-build
        - meson
        - libusb-dev
        - libsqlite3-dev

script:
    - make

